name: path_provider_foundation
publish_to: none
description: iOS and macOS implementation of the path_provider plugin
repository: https://github.com/flutter/packages/tree/main/packages/path_provider/path_provider_foundation
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+path_provider%22
version: 2.3.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

flutter:
  plugin:
    implements: path_provider
    platforms:
      ios:
        pluginClass: PathProviderPlugin
        dartPluginClass: PathProviderFoundation
        sharedDarwinSource: true
      macos:
        pluginClass: PathProviderPlugin
        dartPluginClass: PathProviderFoundation
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  path_provider_platform_interface:
    git: https://github.com/kumsumit/path_provider_platform_interface.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  path: ^1.8.3
  pigeon: 
    git: https://github.com/kumsumit/pigeon.git

topics:
  - files
  - path-provider
  - paths
