name: path_provider_foundation
description: iOS and macOS implementation of the path_provider plugin
repository: https://github.com/flutter/packages/tree/main/packages/path_provider/path_provider_foundation
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+path_provider%22
version: 2.6.0
publish_to: none

environment:
  sdk: ^3.11.3
  flutter: ">=3.41.1"

flutter:
  plugin:
    implements: path_provider
    platforms:
      ios:
        dartPluginClass: PathProviderFoundation
      macos:
        dartPluginClass: PathProviderFoundation

dependencies:
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  objective_c: ^9.3.0
  path_provider_platform_interface:
    git: https://github.com/kumsumit/path_provider_platform_interface.git

dev_dependencies:
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter

topics:
  - files
  - path-provider
  - paths
